### ISSUE TITLE
Show a message when there are no annotations (empty list) for a given language pair

### ISSUE THREAD

**Issue by nandana** [vfrico/mapping-predictor-webapp#2]
As there are no annotations for all language pair, please show a message when the results are empty to let the user know that is was not an error. 

For example, Spanish-Greek, Spanish-Dutch, English-German, etc. 

![screenshot from 2018-08-13 11-30-35](https://user-images.githubusercontent.com/204855/44024116-b44b54ae-9eec-11e8-8309-f6dbc8f8caf9.png)

**Comment by vfrico** [comment]
See commit 98898984af0b2a5ae439a0b064c9b1056e2ccec4
